artifact_uri: file:///c:/Users/Utilisateur/Documents/GitHub/Brief12/MovieWise_Recommender_System/your_mlflow_uri/342564443274030358/cdc82edb9eb649ffafdf84c7feee0a11/artifacts
end_time: 1707840019677
entry_point_name: ''
experiment_id: '342564443274030358'
lifecycle_stage: active
run_id: cdc82edb9eb649ffafdf84c7feee0a11
run_name: adventurous-hare-998
run_uuid: cdc82edb9eb649ffafdf84c7feee0a11
source_name: ''
source_type: 4
source_version: ''
start_time: 1707840018876
status: 3
tags: []
user_id: Utilisateur
