artifact_uri: file:///c:/Users/Utilisateur/Documents/GitHub/Brief12/MovieWise_Recommender_System/your_mlflow_uri/342564443274030358/3e4d5a12e9eb469c99b1068bd3a851eb/artifacts
end_time: 1707839690274
entry_point_name: ''
experiment_id: '342564443274030358'
lifecycle_stage: active
run_id: 3e4d5a12e9eb469c99b1068bd3a851eb
run_name: nervous-crab-393
run_uuid: 3e4d5a12e9eb469c99b1068bd3a851eb
source_name: ''
source_type: 4
source_version: ''
start_time: 1707839688521
status: 3
tags: []
user_id: Utilisateur
