artifact_uri: file:///c:/Users/Utilisateur/Documents/GitHub/Brief12/MovieWise_Recommender_System/your_mlflow_uri/342564443274030358/caa8d5192790483ea7fc78b8fcd8bb70/artifacts
end_time: 1707839827603
entry_point_name: ''
experiment_id: '342564443274030358'
lifecycle_stage: active
run_id: caa8d5192790483ea7fc78b8fcd8bb70
run_name: bouncy-skunk-964
run_uuid: caa8d5192790483ea7fc78b8fcd8bb70
source_name: ''
source_type: 4
source_version: ''
start_time: 1707839826763
status: 3
tags: []
user_id: Utilisateur
