artifact_uri: file:///c:/Users/Utilisateur/Documents/GitHub/Brief12/MovieWise_Recommender_System/your_mlflow_uri/342564443274030358/ae81e38919fe43b6bd5dd26daad78554/artifacts
end_time: 1707839809761
entry_point_name: ''
experiment_id: '342564443274030358'
lifecycle_stage: active
run_id: ae81e38919fe43b6bd5dd26daad78554
run_name: redolent-colt-188
run_uuid: ae81e38919fe43b6bd5dd26daad78554
source_name: ''
source_type: 4
source_version: ''
start_time: 1707839808485
status: 3
tags: []
user_id: Utilisateur
