artifact_uri: file:///c:/Users/Utilisateur/Documents/GitHub/Brief12/MovieWise_Recommender_System/your_mlflow_uri/342564443274030358/d60355d17d654fbd852ae92ec7a0a8e4/artifacts
end_time: 1707839610145
entry_point_name: ''
experiment_id: '342564443274030358'
lifecycle_stage: active
run_id: d60355d17d654fbd852ae92ec7a0a8e4
run_name: flawless-fawn-695
run_uuid: d60355d17d654fbd852ae92ec7a0a8e4
source_name: ''
source_type: 4
source_version: ''
start_time: 1707839609347
status: 3
tags: []
user_id: Utilisateur
