artifact_uri: file:///c:/Users/Utilisateur/Documents/GitHub/Brief12/MovieWise_Recommender_System/your_mlflow_uri/342564443274030358/ebd2cb70e5234a9391b7aa4f391dffab/artifacts
end_time: 1707840045618
entry_point_name: ''
experiment_id: '342564443274030358'
lifecycle_stage: active
run_id: ebd2cb70e5234a9391b7aa4f391dffab
run_name: whimsical-mink-214
run_uuid: ebd2cb70e5234a9391b7aa4f391dffab
source_name: ''
source_type: 4
source_version: ''
start_time: 1707840043811
status: 3
tags: []
user_id: Utilisateur
