artifact_uri: file:///c:/Users/Utilisateur/Documents/GitHub/Brief12/MovieWise_Recommender_System/your_mlflow_uri/342564443274030358/2b27b835412a4fd9abe16a84aec4ef19/artifacts
end_time: 1707839662342
entry_point_name: ''
experiment_id: '342564443274030358'
lifecycle_stage: active
run_id: 2b27b835412a4fd9abe16a84aec4ef19
run_name: enthused-shrike-522
run_uuid: 2b27b835412a4fd9abe16a84aec4ef19
source_name: ''
source_type: 4
source_version: ''
start_time: 1707839661372
status: 3
tags: []
user_id: Utilisateur
