artifact_uri: file:///c:/Users/Utilisateur/Documents/GitHub/Brief12/MovieWise_Recommender_System/your_mlflow_uri/342564443274030358/a2f543fd8de447caa3f2d1e684e07f63/artifacts
end_time: 1707840007450
entry_point_name: ''
experiment_id: '342564443274030358'
lifecycle_stage: active
run_id: a2f543fd8de447caa3f2d1e684e07f63
run_name: gentle-lynx-644
run_uuid: a2f543fd8de447caa3f2d1e684e07f63
source_name: ''
source_type: 4
source_version: ''
start_time: 1707840006958
status: 3
tags: []
user_id: Utilisateur
