artifact_uri: file:///c:/Users/Utilisateur/Documents/GitHub/Brief12/MovieWise_Recommender_System/your_mlflow_uri/342564443274030358/d30ae279da8544f3b3737d58cac2b5ed/artifacts
end_time: 1707839675385
entry_point_name: ''
experiment_id: '342564443274030358'
lifecycle_stage: active
run_id: d30ae279da8544f3b3737d58cac2b5ed
run_name: delicate-pig-750
run_uuid: d30ae279da8544f3b3737d58cac2b5ed
source_name: ''
source_type: 4
source_version: ''
start_time: 1707839673671
status: 3
tags: []
user_id: Utilisateur
