artifact_uri: file:///c:/Users/Utilisateur/Documents/GitHub/Brief12/MovieWise_Recommender_System/your_mlflow_uri/342564443274030358/99fc2aef77d449868898dfbcca77e0b7/artifacts
end_time: 1707839812278
entry_point_name: ''
experiment_id: '342564443274030358'
lifecycle_stage: active
run_id: 99fc2aef77d449868898dfbcca77e0b7
run_name: unequaled-midge-896
run_uuid: 99fc2aef77d449868898dfbcca77e0b7
source_name: ''
source_type: 4
source_version: ''
start_time: 1707839810678
status: 3
tags: []
user_id: Utilisateur
