artifact_uri: file:///c:/Users/Utilisateur/Documents/GitHub/Brief12/MovieWise_Recommender_System/your_mlflow_uri/342564443274030358/fc996930c9714dbeb7b01aeb7c3ac749/artifacts
end_time: 1707840032433
entry_point_name: ''
experiment_id: '342564443274030358'
lifecycle_stage: active
run_id: fc996930c9714dbeb7b01aeb7c3ac749
run_name: unique-fly-860
run_uuid: fc996930c9714dbeb7b01aeb7c3ac749
source_name: ''
source_type: 4
source_version: ''
start_time: 1707840030918
status: 3
tags: []
user_id: Utilisateur
