artifact_uri: file:///c:/Users/Utilisateur/Documents/GitHub/Brief12/MovieWise_Recommender_System/your_mlflow_uri/342564443274030358/3b477a04080c49dd8dcfa333aa9c3ccb/artifacts
end_time: 1707840111310
entry_point_name: ''
experiment_id: '342564443274030358'
lifecycle_stage: active
run_id: 3b477a04080c49dd8dcfa333aa9c3ccb
run_name: exultant-seal-890
run_uuid: 3b477a04080c49dd8dcfa333aa9c3ccb
source_name: ''
source_type: 4
source_version: ''
start_time: 1707840110557
status: 3
tags: []
user_id: Utilisateur
