artifact_uri: file:///c:/Users/Utilisateur/Documents/GitHub/Brief12/MovieWise_Recommender_System/your_mlflow_uri/342564443274030358/a7eace4aabc54a93846d0cd20e383fda/artifacts
end_time: 1707839810662
entry_point_name: ''
experiment_id: '342564443274030358'
lifecycle_stage: active
run_id: a7eace4aabc54a93846d0cd20e383fda
run_name: amusing-squid-158
run_uuid: a7eace4aabc54a93846d0cd20e383fda
source_name: ''
source_type: 4
source_version: ''
start_time: 1707839809770
status: 3
tags: []
user_id: Utilisateur
