artifact_uri: file:///c:/Users/Utilisateur/Documents/GitHub/Brief12/MovieWise_Recommender_System/your_mlflow_uri/342564443274030358/942e94bb8c0f4415920ed00ef0aca5cd/artifacts
end_time: 1707840039905
entry_point_name: ''
experiment_id: '342564443274030358'
lifecycle_stage: active
run_id: 942e94bb8c0f4415920ed00ef0aca5cd
run_name: dapper-kit-46
run_uuid: 942e94bb8c0f4415920ed00ef0aca5cd
source_name: ''
source_type: 4
source_version: ''
start_time: 1707840037348
status: 3
tags: []
user_id: Utilisateur
