artifact_uri: file:///c:/Users/Utilisateur/Documents/GitHub/Brief12/MovieWise_Recommender_System/your_mlflow_uri/342564443274030358/cedf0e7161854cd096abfae570af6713/artifacts
end_time: 1707839999463
entry_point_name: ''
experiment_id: '342564443274030358'
lifecycle_stage: active
run_id: cedf0e7161854cd096abfae570af6713
run_name: awesome-crow-482
run_uuid: cedf0e7161854cd096abfae570af6713
source_name: ''
source_type: 4
source_version: ''
start_time: 1707839998984
status: 3
tags: []
user_id: Utilisateur
