artifact_uri: file:///c:/Users/Utilisateur/Documents/GitHub/Brief12/MovieWise_Recommender_System/your_mlflow_uri/342564443274030358/9ca0232be61d40d2bdc53908d4ac6da5/artifacts
end_time: 1707839615380
entry_point_name: ''
experiment_id: '342564443274030358'
lifecycle_stage: active
run_id: 9ca0232be61d40d2bdc53908d4ac6da5
run_name: receptive-mare-674
run_uuid: 9ca0232be61d40d2bdc53908d4ac6da5
source_name: ''
source_type: 4
source_version: ''
start_time: 1707839614399
status: 3
tags: []
user_id: Utilisateur
