artifact_uri: file:///c:/Users/Utilisateur/Documents/GitHub/Brief12/MovieWise_Recommender_System/your_mlflow_uri/342564443274030358/cbd8e2d0c9484d7a8d1d0c292ed9594d/artifacts
end_time: 1707839804727
entry_point_name: ''
experiment_id: '342564443274030358'
lifecycle_stage: active
run_id: cbd8e2d0c9484d7a8d1d0c292ed9594d
run_name: mercurial-lamb-822
run_uuid: cbd8e2d0c9484d7a8d1d0c292ed9594d
source_name: ''
source_type: 4
source_version: ''
start_time: 1707839803248
status: 3
tags: []
user_id: Utilisateur
