artifact_uri: file:///c:/Users/Utilisateur/Documents/GitHub/Brief12/MovieWise_Recommender_System/your_mlflow_uri/342564443274030358/4487ee8250db4e6e8768e6b7dc2ef53c/artifacts
end_time: 1707839649574
entry_point_name: ''
experiment_id: '342564443274030358'
lifecycle_stage: active
run_id: 4487ee8250db4e6e8768e6b7dc2ef53c
run_name: persistent-lamb-911
run_uuid: 4487ee8250db4e6e8768e6b7dc2ef53c
source_name: ''
source_type: 4
source_version: ''
start_time: 1707839649098
status: 3
tags: []
user_id: Utilisateur
