artifact_uri: file:///c:/Users/Utilisateur/Documents/GitHub/Brief12/MovieWise_Recommender_System/your_mlflow_uri/342564443274030358/7d46e95750e744fbad7b84678cadea5f/artifacts
end_time: 1707839881026
entry_point_name: ''
experiment_id: '342564443274030358'
lifecycle_stage: active
run_id: 7d46e95750e744fbad7b84678cadea5f
run_name: gentle-slug-288
run_uuid: 7d46e95750e744fbad7b84678cadea5f
source_name: ''
source_type: 4
source_version: ''
start_time: 1707839880215
status: 3
tags: []
user_id: Utilisateur
