artifact_uri: file:///c:/Users/Utilisateur/Documents/GitHub/Brief12/MovieWise_Recommender_System/your_mlflow_uri/342564443274030358/fe23aa7cff224d5da2d0acc4759dff2d/artifacts
end_time: 1707840108946
entry_point_name: ''
experiment_id: '342564443274030358'
lifecycle_stage: active
run_id: fe23aa7cff224d5da2d0acc4759dff2d
run_name: intelligent-shad-581
run_uuid: fe23aa7cff224d5da2d0acc4759dff2d
source_name: ''
source_type: 4
source_version: ''
start_time: 1707840108158
status: 3
tags: []
user_id: Utilisateur
