artifact_uri: file:///c:/Users/Utilisateur/Documents/GitHub/Brief12/MovieWise_Recommender_System/your_mlflow_uri/342564443274030358/4cd528a8d41d4c39aa748f6abcbb9f92/artifacts
end_time: 1707839659312
entry_point_name: ''
experiment_id: '342564443274030358'
lifecycle_stage: active
run_id: 4cd528a8d41d4c39aa748f6abcbb9f92
run_name: nosy-cub-775
run_uuid: 4cd528a8d41d4c39aa748f6abcbb9f92
source_name: ''
source_type: 4
source_version: ''
start_time: 1707839658895
status: 3
tags: []
user_id: Utilisateur
