artifact_uri: file:///c:/Users/Utilisateur/Documents/GitHub/Brief12/MovieWise_Recommender_System/your_mlflow_uri/342564443274030358/92ad24ace91c4d7db81c28a713ce6aed/artifacts
end_time: 1707840064118
entry_point_name: ''
experiment_id: '342564443274030358'
lifecycle_stage: active
run_id: 92ad24ace91c4d7db81c28a713ce6aed
run_name: bouncy-ape-542
run_uuid: 92ad24ace91c4d7db81c28a713ce6aed
source_name: ''
source_type: 4
source_version: ''
start_time: 1707840063666
status: 3
tags: []
user_id: Utilisateur
