artifact_uri: file:///c:/Users/Utilisateur/Documents/GitHub/Brief12/MovieWise_Recommender_System/your_mlflow_uri/342564443274030358/d7d31dd08bf745028d01bb2b73e61ed1/artifacts
end_time: 1707840025789
entry_point_name: ''
experiment_id: '342564443274030358'
lifecycle_stage: active
run_id: d7d31dd08bf745028d01bb2b73e61ed1
run_name: marvelous-grouse-169
run_uuid: d7d31dd08bf745028d01bb2b73e61ed1
source_name: ''
source_type: 4
source_version: ''
start_time: 1707840025396
status: 3
tags: []
user_id: Utilisateur
