artifact_uri: file:///c:/Users/Utilisateur/Documents/GitHub/Brief12/MovieWise_Recommender_System/your_mlflow_uri/342564443274030358/bcbce3ffa46440e78d58ec0ae5bfbd09/artifacts
end_time: 1707839653350
entry_point_name: ''
experiment_id: '342564443274030358'
lifecycle_stage: active
run_id: bcbce3ffa46440e78d58ec0ae5bfbd09
run_name: upbeat-sow-181
run_uuid: bcbce3ffa46440e78d58ec0ae5bfbd09
source_name: ''
source_type: 4
source_version: ''
start_time: 1707839652373
status: 3
tags: []
user_id: Utilisateur
