artifact_uri: file:///c:/Users/Utilisateur/Documents/GitHub/Brief12/MovieWise_Recommender_System/your_mlflow_uri/342564443274030358/4ae7b15049d84492ac770eb11ccb9e0f/artifacts
end_time: 1707840071600
entry_point_name: ''
experiment_id: '342564443274030358'
lifecycle_stage: active
run_id: 4ae7b15049d84492ac770eb11ccb9e0f
run_name: unequaled-steed-209
run_uuid: 4ae7b15049d84492ac770eb11ccb9e0f
source_name: ''
source_type: 4
source_version: ''
start_time: 1707840071124
status: 3
tags: []
user_id: Utilisateur
