artifact_uri: file:///c:/Users/Utilisateur/Documents/GitHub/Brief12/MovieWise_Recommender_System/your_mlflow_uri/342564443274030358/6a98f7bdc2d7447eb98690afeeca15f0/artifacts
end_time: 1707839629773
entry_point_name: ''
experiment_id: '342564443274030358'
lifecycle_stage: active
run_id: 6a98f7bdc2d7447eb98690afeeca15f0
run_name: upset-hawk-617
run_uuid: 6a98f7bdc2d7447eb98690afeeca15f0
source_name: ''
source_type: 4
source_version: ''
start_time: 1707839628984
status: 3
tags: []
user_id: Utilisateur
