artifact_uri: file:///c:/Users/Utilisateur/Documents/GitHub/Brief12/MovieWise_Recommender_System/your_mlflow_uri/342564443274030358/383da1dfffd34d209f584c9729daa7ce/artifacts
end_time: 1707839896693
entry_point_name: ''
experiment_id: '342564443274030358'
lifecycle_stage: active
run_id: 383da1dfffd34d209f584c9729daa7ce
run_name: merciful-panda-40
run_uuid: 383da1dfffd34d209f584c9729daa7ce
source_name: ''
source_type: 4
source_version: ''
start_time: 1707839895832
status: 3
tags: []
user_id: Utilisateur
