artifact_uri: file:///c:/Users/Utilisateur/Documents/GitHub/Brief12/MovieWise_Recommender_System/your_mlflow_uri/342564443274030358/c2b95710e70d4ec6ae941278eccfbc78/artifacts
end_time: 1707839917307
entry_point_name: ''
experiment_id: '342564443274030358'
lifecycle_stage: active
run_id: c2b95710e70d4ec6ae941278eccfbc78
run_name: industrious-wolf-970
run_uuid: c2b95710e70d4ec6ae941278eccfbc78
source_name: ''
source_type: 4
source_version: ''
start_time: 1707839916824
status: 3
tags: []
user_id: Utilisateur
