artifact_uri: file:///c:/Users/Utilisateur/Documents/GitHub/Brief12/MovieWise_Recommender_System/your_mlflow_uri/342564443274030358/920d2606e86f495ea27aebe8ec4dd5b5/artifacts
end_time: 1707839837903
entry_point_name: ''
experiment_id: '342564443274030358'
lifecycle_stage: active
run_id: 920d2606e86f495ea27aebe8ec4dd5b5
run_name: mercurial-tern-755
run_uuid: 920d2606e86f495ea27aebe8ec4dd5b5
source_name: ''
source_type: 4
source_version: ''
start_time: 1707839837446
status: 3
tags: []
user_id: Utilisateur
