artifact_uri: file:///c:/Users/Utilisateur/Documents/GitHub/Brief12/MovieWise_Recommender_System/your_mlflow_uri/342564443274030358/35fa904ce55a41859abd404a73cc71cc/artifacts
end_time: 1707839824413
entry_point_name: ''
experiment_id: '342564443274030358'
lifecycle_stage: active
run_id: 35fa904ce55a41859abd404a73cc71cc
run_name: overjoyed-fly-925
run_uuid: 35fa904ce55a41859abd404a73cc71cc
source_name: ''
source_type: 4
source_version: ''
start_time: 1707839822834
status: 3
tags: []
user_id: Utilisateur
