artifact_uri: file:///c:/Users/Utilisateur/Documents/GitHub/Brief12/MovieWise_Recommender_System/your_mlflow_uri/342564443274030358/87ac82fd2c0b4259b04ed06d5bb16e37/artifacts
end_time: 1707839603880
entry_point_name: ''
experiment_id: '342564443274030358'
lifecycle_stage: active
run_id: 87ac82fd2c0b4259b04ed06d5bb16e37
run_name: clumsy-grub-185
run_uuid: 87ac82fd2c0b4259b04ed06d5bb16e37
source_name: ''
source_type: 4
source_version: ''
start_time: 1707839602737
status: 3
tags: []
user_id: Utilisateur
