artifact_uri: file:///c:/Users/Utilisateur/Documents/GitHub/Brief12/MovieWise_Recommender_System/your_mlflow_uri/342564443274030358/f630fe318c4f4c44afb972a1e17a3c8b/artifacts
end_time: 1707839915116
entry_point_name: ''
experiment_id: '342564443274030358'
lifecycle_stage: active
run_id: f630fe318c4f4c44afb972a1e17a3c8b
run_name: funny-sow-105
run_uuid: f630fe318c4f4c44afb972a1e17a3c8b
source_name: ''
source_type: 4
source_version: ''
start_time: 1707839914660
status: 3
tags: []
user_id: Utilisateur
