artifact_uri: file:///c:/Users/Utilisateur/Documents/GitHub/Brief12/MovieWise_Recommender_System/your_mlflow_uri/342564443274030358/9abfd303c7f04c02ae45c65f2d6dbf58/artifacts
end_time: 1707839829198
entry_point_name: ''
experiment_id: '342564443274030358'
lifecycle_stage: active
run_id: 9abfd303c7f04c02ae45c65f2d6dbf58
run_name: chill-colt-915
run_uuid: 9abfd303c7f04c02ae45c65f2d6dbf58
source_name: ''
source_type: 4
source_version: ''
start_time: 1707839827617
status: 3
tags: []
user_id: Utilisateur
