artifact_uri: file:///c:/Users/Utilisateur/Documents/GitHub/Brief12/MovieWise_Recommender_System/your_mlflow_uri/342564443274030358/f4ad38f3a5724e4196e092c6cd81bd8e/artifacts
end_time: 1707839820663
entry_point_name: ''
experiment_id: '342564443274030358'
lifecycle_stage: active
run_id: f4ad38f3a5724e4196e092c6cd81bd8e
run_name: welcoming-stork-660
run_uuid: f4ad38f3a5724e4196e092c6cd81bd8e
source_name: ''
source_type: 4
source_version: ''
start_time: 1707839819996
status: 3
tags: []
user_id: Utilisateur
