artifact_uri: file:///c:/Users/Utilisateur/Documents/GitHub/Brief12/MovieWise_Recommender_System/your_mlflow_uri/342564443274030358/28ddf1c973424eb596db307580c70d8d/artifacts
end_time: null
entry_point_name: ''
experiment_id: '342564443274030358'
lifecycle_stage: active
run_id: 28ddf1c973424eb596db307580c70d8d
run_name: silent-owl-712
run_uuid: 28ddf1c973424eb596db307580c70d8d
source_name: ''
source_type: 4
source_version: ''
start_time: 1707840071617
status: 1
tags: []
user_id: Utilisateur
