artifact_uri: file:///c:/Users/Utilisateur/Documents/GitHub/Brief12/MovieWise_Recommender_System/your_mlflow_uri/342564443274030358/ca2ace96e9df4e4bbbfcac023c5eabd9/artifacts
end_time: 1707840110546
entry_point_name: ''
experiment_id: '342564443274030358'
lifecycle_stage: active
run_id: ca2ace96e9df4e4bbbfcac023c5eabd9
run_name: bedecked-zebra-729
run_uuid: ca2ace96e9df4e4bbbfcac023c5eabd9
source_name: ''
source_type: 4
source_version: ''
start_time: 1707840109761
status: 3
tags: []
user_id: Utilisateur
