artifact_uri: file:///c:/Users/Utilisateur/Documents/GitHub/Brief12/MovieWise_Recommender_System/your_mlflow_uri/342564443274030358/bab1997d56f34966b7dee994ad579e4e/artifacts
end_time: 1707840029394
entry_point_name: ''
experiment_id: '342564443274030358'
lifecycle_stage: active
run_id: bab1997d56f34966b7dee994ad579e4e
run_name: blushing-snipe-451
run_uuid: bab1997d56f34966b7dee994ad579e4e
source_name: ''
source_type: 4
source_version: ''
start_time: 1707840027982
status: 3
tags: []
user_id: Utilisateur
