artifact_uri: file:///c:/Users/Utilisateur/Documents/GitHub/Brief12/MovieWise_Recommender_System/your_mlflow_uri/342564443274030358/27bb6fa43dcc4ac2b1ed4432f7a1a885/artifacts
end_time: 1707840009644
entry_point_name: ''
experiment_id: '342564443274030358'
lifecycle_stage: active
run_id: 27bb6fa43dcc4ac2b1ed4432f7a1a885
run_name: rumbling-foal-474
run_uuid: 27bb6fa43dcc4ac2b1ed4432f7a1a885
source_name: ''
source_type: 4
source_version: ''
start_time: 1707840008164
status: 3
tags: []
user_id: Utilisateur
