artifact_uri: file:///c:/Users/Utilisateur/Documents/GitHub/Brief12/MovieWise_Recommender_System/your_mlflow_uri/342564443274030358/96fcfdfe9c8844e595b452e1e5923cf6/artifacts
end_time: 1707840062736
entry_point_name: ''
experiment_id: '342564443274030358'
lifecycle_stage: active
run_id: 96fcfdfe9c8844e595b452e1e5923cf6
run_name: smiling-bass-306
run_uuid: 96fcfdfe9c8844e595b452e1e5923cf6
source_name: ''
source_type: 4
source_version: ''
start_time: 1707840061911
status: 3
tags: []
user_id: Utilisateur
