artifact_uri: file:///c:/Users/Utilisateur/Documents/GitHub/Brief12/MovieWise_Recommender_System/your_mlflow_uri/342564443274030358/b99b8dcd0c674bf08afbe7de310dc085/artifacts
end_time: 1707839597817
entry_point_name: ''
experiment_id: '342564443274030358'
lifecycle_stage: active
run_id: b99b8dcd0c674bf08afbe7de310dc085
run_name: blushing-fly-787
run_uuid: b99b8dcd0c674bf08afbe7de310dc085
source_name: ''
source_type: 4
source_version: ''
start_time: 1707839596790
status: 3
tags: []
user_id: Utilisateur
