artifact_uri: file:///c:/Users/Utilisateur/Documents/GitHub/Brief12/MovieWise_Recommender_System/your_mlflow_uri/342564443274030358/1dc2f7fd80d94742813f6ddec526d6a0/artifacts
end_time: 1707840061895
entry_point_name: ''
experiment_id: '342564443274030358'
lifecycle_stage: active
run_id: 1dc2f7fd80d94742813f6ddec526d6a0
run_name: skillful-hound-309
run_uuid: 1dc2f7fd80d94742813f6ddec526d6a0
source_name: ''
source_type: 4
source_version: ''
start_time: 1707840061466
status: 3
tags: []
user_id: Utilisateur
