artifact_uri: file:///c:/Users/Utilisateur/Documents/GitHub/Brief12/MovieWise_Recommender_System/your_mlflow_uri/342564443274030358/dc479ac7e4ca4148beb17915f3ac2cc1/artifacts
end_time: 1707839837431
entry_point_name: ''
experiment_id: '342564443274030358'
lifecycle_stage: active
run_id: dc479ac7e4ca4148beb17915f3ac2cc1
run_name: powerful-stoat-479
run_uuid: dc479ac7e4ca4148beb17915f3ac2cc1
source_name: ''
source_type: 4
source_version: ''
start_time: 1707839836564
status: 3
tags: []
user_id: Utilisateur
