artifact_uri: file:///c:/Users/Utilisateur/Documents/GitHub/Brief12/MovieWise_Recommender_System/your_mlflow_uri/342564443274030358/7464adaec73847c3bb2d1b017e87a3a0/artifacts
end_time: 1707839866182
entry_point_name: ''
experiment_id: '342564443274030358'
lifecycle_stage: active
run_id: 7464adaec73847c3bb2d1b017e87a3a0
run_name: worried-loon-545
run_uuid: 7464adaec73847c3bb2d1b017e87a3a0
source_name: ''
source_type: 4
source_version: ''
start_time: 1707839865394
status: 3
tags: []
user_id: Utilisateur
