artifact_uri: file:///c:/Users/Utilisateur/Documents/GitHub/Brief12/MovieWise_Recommender_System/your_mlflow_uri/342564443274030358/3cb155d2b5cf494aa566f40b79f94bad/artifacts
end_time: 1707839699456
entry_point_name: ''
experiment_id: '342564443274030358'
lifecycle_stage: active
run_id: 3cb155d2b5cf494aa566f40b79f94bad
run_name: overjoyed-boar-140
run_uuid: 3cb155d2b5cf494aa566f40b79f94bad
source_name: ''
source_type: 4
source_version: ''
start_time: 1707839696727
status: 3
tags: []
user_id: Utilisateur
