artifact_uri: file:///c:/Users/Utilisateur/Documents/GitHub/Brief12/MovieWise_Recommender_System/your_mlflow_uri/342564443274030358/d9d4a7d6eec54d68b41eec12c26cdd94/artifacts
end_time: 1707839594511
entry_point_name: ''
experiment_id: '342564443274030358'
lifecycle_stage: active
run_id: d9d4a7d6eec54d68b41eec12c26cdd94
run_name: salty-wren-216
run_uuid: d9d4a7d6eec54d68b41eec12c26cdd94
source_name: ''
source_type: 4
source_version: ''
start_time: 1707839594033
status: 3
tags: []
user_id: Utilisateur
