artifact_uri: file:///c:/Users/Utilisateur/Documents/GitHub/Brief12/MovieWise_Recommender_System/your_mlflow_uri/342564443274030358/309eb9ef42fe466abe113e8c3bfe885d/artifacts
end_time: 1707839904806
entry_point_name: ''
experiment_id: '342564443274030358'
lifecycle_stage: active
run_id: 309eb9ef42fe466abe113e8c3bfe885d
run_name: aged-lark-27
run_uuid: 309eb9ef42fe466abe113e8c3bfe885d
source_name: ''
source_type: 4
source_version: ''
start_time: 1707839901694
status: 3
tags: []
user_id: Utilisateur
