artifact_uri: file:///c:/Users/Utilisateur/Documents/GitHub/Brief12/MovieWise_Recommender_System/your_mlflow_uri/342564443274030358/eb5694027b9b47faab1f533947b11bbb/artifacts
end_time: 1707840051303
entry_point_name: ''
experiment_id: '342564443274030358'
lifecycle_stage: active
run_id: eb5694027b9b47faab1f533947b11bbb
run_name: languid-snake-472
run_uuid: eb5694027b9b47faab1f533947b11bbb
source_name: ''
source_type: 4
source_version: ''
start_time: 1707840050003
status: 3
tags: []
user_id: Utilisateur
