artifact_uri: file:///c:/Users/Utilisateur/Documents/GitHub/Brief12/MovieWise_Recommender_System/your_mlflow_uri/342564443274030358/d4f6157d9666437bb7dfe5b0f900a8de/artifacts
end_time: 1707840006377
entry_point_name: ''
experiment_id: '342564443274030358'
lifecycle_stage: active
run_id: d4f6157d9666437bb7dfe5b0f900a8de
run_name: redolent-hawk-948
run_uuid: d4f6157d9666437bb7dfe5b0f900a8de
source_name: ''
source_type: 4
source_version: ''
start_time: 1707840004843
status: 3
tags: []
user_id: Utilisateur
