artifact_uri: file:///c:/Users/Utilisateur/Documents/GitHub/Brief12/MovieWise_Recommender_System/your_mlflow_uri/342564443274030358/38c45db4e0ef4f678af4a3a9f2968e72/artifacts
end_time: 1707839717812
entry_point_name: ''
experiment_id: '342564443274030358'
lifecycle_stage: active
run_id: 38c45db4e0ef4f678af4a3a9f2968e72
run_name: fearless-bee-741
run_uuid: 38c45db4e0ef4f678af4a3a9f2968e72
source_name: ''
source_type: 4
source_version: ''
start_time: 1707839717361
status: 3
tags: []
user_id: Utilisateur
