artifact_uri: file:///c:/Users/Utilisateur/Documents/GitHub/Brief12/MovieWise_Recommender_System/your_mlflow_uri/342564443274030358/171bd05ec1d048cdaa8e45b2fcb286c4/artifacts
end_time: 1707839705317
entry_point_name: ''
experiment_id: '342564443274030358'
lifecycle_stage: active
run_id: 171bd05ec1d048cdaa8e45b2fcb286c4
run_name: redolent-pug-750
run_uuid: 171bd05ec1d048cdaa8e45b2fcb286c4
source_name: ''
source_type: 4
source_version: ''
start_time: 1707839702520
status: 3
tags: []
user_id: Utilisateur
