artifact_uri: file:///c:/Users/Utilisateur/Documents/GitHub/Brief12/MovieWise_Recommender_System/your_mlflow_uri/342564443274030358/cf04ebca137f4de89d06a83d5ad96629/artifacts
end_time: 1707840100837
entry_point_name: ''
experiment_id: '342564443274030358'
lifecycle_stage: active
run_id: cf04ebca137f4de89d06a83d5ad96629
run_name: rogue-snake-693
run_uuid: cf04ebca137f4de89d06a83d5ad96629
source_name: ''
source_type: 4
source_version: ''
start_time: 1707840100404
status: 3
tags: []
user_id: Utilisateur
