artifact_uri: file:///c:/Users/Utilisateur/Documents/GitHub/Brief12/MovieWise_Recommender_System/your_mlflow_uri/342564443274030358/ee5ff930a3f64dd496fd2ded191bd385/artifacts
end_time: 1707840024519
entry_point_name: ''
experiment_id: '342564443274030358'
lifecycle_stage: active
run_id: ee5ff930a3f64dd496fd2ded191bd385
run_name: classy-cow-763
run_uuid: ee5ff930a3f64dd496fd2ded191bd385
source_name: ''
source_type: 4
source_version: ''
start_time: 1707840023038
status: 3
tags: []
user_id: Utilisateur
