artifact_uri: file:///c:/Users/Utilisateur/Documents/GitHub/Brief12/MovieWise_Recommender_System/your_mlflow_uri/342564443274030358/5b679edf5dba45658cbf2a48e873f823/artifacts
end_time: 1707840065671
entry_point_name: ''
experiment_id: '342564443274030358'
lifecycle_stage: active
run_id: 5b679edf5dba45658cbf2a48e873f823
run_name: abrasive-asp-659
run_uuid: 5b679edf5dba45658cbf2a48e873f823
source_name: ''
source_type: 4
source_version: ''
start_time: 1707840064789
status: 3
tags: []
user_id: Utilisateur
