artifact_uri: file:///c:/Users/Utilisateur/Documents/GitHub/Brief12/MovieWise_Recommender_System/your_mlflow_uri/342564443274030358/0c07c6bf71a34b85bac15d582cc6be09/artifacts
end_time: 1707840067896
entry_point_name: ''
experiment_id: '342564443274030358'
lifecycle_stage: active
run_id: 0c07c6bf71a34b85bac15d582cc6be09
run_name: classy-mole-630
run_uuid: 0c07c6bf71a34b85bac15d582cc6be09
source_name: ''
source_type: 4
source_version: ''
start_time: 1707840067041
status: 3
tags: []
user_id: Utilisateur
