artifact_uri: file:///c:/Users/Utilisateur/Documents/GitHub/Brief12/MovieWise_Recommender_System/your_mlflow_uri/342564443274030358/7b2152d48e764bf2b59f52eddc30feb6/artifacts
end_time: 1707839895798
entry_point_name: ''
experiment_id: '342564443274030358'
lifecycle_stage: active
run_id: 7b2152d48e764bf2b59f52eddc30feb6
run_name: upset-sloth-661
run_uuid: 7b2152d48e764bf2b59f52eddc30feb6
source_name: ''
source_type: 4
source_version: ''
start_time: 1707839895017
status: 3
tags: []
user_id: Utilisateur
