artifact_uri: file:///c:/Users/Utilisateur/Documents/GitHub/Brief12/MovieWise_Recommender_System/your_mlflow_uri/342564443274030358/37cf739c5aa94c418e5afbe2d39266d6/artifacts
end_time: 1707839688492
entry_point_name: ''
experiment_id: '342564443274030358'
lifecycle_stage: active
run_id: 37cf739c5aa94c418e5afbe2d39266d6
run_name: gregarious-rat-414
run_uuid: 37cf739c5aa94c418e5afbe2d39266d6
source_name: ''
source_type: 4
source_version: ''
start_time: 1707839685668
status: 3
tags: []
user_id: Utilisateur
