artifact_uri: file:///c:/Users/Utilisateur/Documents/GitHub/Brief12/MovieWise_Recommender_System/your_mlflow_uri/342564443274030358/72cb0fb4bc2d408b8f580f25336ce35f/artifacts
end_time: 1707839912838
entry_point_name: ''
experiment_id: '342564443274030358'
lifecycle_stage: active
run_id: 72cb0fb4bc2d408b8f580f25336ce35f
run_name: enthused-fox-622
run_uuid: 72cb0fb4bc2d408b8f580f25336ce35f
source_name: ''
source_type: 4
source_version: ''
start_time: 1707839912203
status: 3
tags: []
user_id: Utilisateur
