artifact_uri: file:///c:/Users/Utilisateur/Documents/GitHub/Brief12/MovieWise_Recommender_System/your_mlflow_uri/342564443274030358/090f57486fe94db580fd5e2bffaac4dd/artifacts
end_time: 1707840006933
entry_point_name: ''
experiment_id: '342564443274030358'
lifecycle_stage: active
run_id: 090f57486fe94db580fd5e2bffaac4dd
run_name: thundering-mole-342
run_uuid: 090f57486fe94db580fd5e2bffaac4dd
source_name: ''
source_type: 4
source_version: ''
start_time: 1707840006392
status: 3
tags: []
user_id: Utilisateur
