artifact_uri: file:///c:/Users/Utilisateur/Documents/GitHub/Brief12/MovieWise_Recommender_System/your_mlflow_uri/342564443274030358/98abeed44f074fc19b547a21e2289ac8/artifacts
end_time: 1707840018860
entry_point_name: ''
experiment_id: '342564443274030358'
lifecycle_stage: active
run_id: 98abeed44f074fc19b547a21e2289ac8
run_name: bedecked-slug-845
run_uuid: 98abeed44f074fc19b547a21e2289ac8
source_name: ''
source_type: 4
source_version: ''
start_time: 1707840017943
status: 3
tags: []
user_id: Utilisateur
