artifact_uri: file:///c:/Users/Utilisateur/Documents/GitHub/Brief12/MovieWise_Recommender_System/your_mlflow_uri/342564443274030358/2337b98e94bf48e0a96ef0b88c12fe4d/artifacts
end_time: 1707839680101
entry_point_name: ''
experiment_id: '342564443274030358'
lifecycle_stage: active
run_id: 2337b98e94bf48e0a96ef0b88c12fe4d
run_name: suave-sheep-450
run_uuid: 2337b98e94bf48e0a96ef0b88c12fe4d
source_name: ''
source_type: 4
source_version: ''
start_time: 1707839678863
status: 3
tags: []
user_id: Utilisateur
