artifact_uri: file:///c:/Users/Utilisateur/Documents/GitHub/Brief12/MovieWise_Recommender_System/your_mlflow_uri/342564443274030358/a7972f2735b348c0bac23207bb7efb5d/artifacts
end_time: 1707840100390
entry_point_name: ''
experiment_id: '342564443274030358'
lifecycle_stage: active
run_id: a7972f2735b348c0bac23207bb7efb5d
run_name: adorable-hawk-606
run_uuid: a7972f2735b348c0bac23207bb7efb5d
source_name: ''
source_type: 4
source_version: ''
start_time: 1707840099003
status: 3
tags: []
user_id: Utilisateur
