artifact_uri: file:///c:/Users/Utilisateur/Documents/GitHub/Brief12/MovieWise_Recommender_System/your_mlflow_uri/342564443274030358/e269b4c864ab4fcfb00710d0b88ee0ef/artifacts
end_time: 1707840020568
entry_point_name: ''
experiment_id: '342564443274030358'
lifecycle_stage: active
run_id: e269b4c864ab4fcfb00710d0b88ee0ef
run_name: mercurial-wasp-985
run_uuid: e269b4c864ab4fcfb00710d0b88ee0ef
source_name: ''
source_type: 4
source_version: ''
start_time: 1707840019689
status: 3
tags: []
user_id: Utilisateur
