artifact_location: file:///c:/Users/Utilisateur/Documents/GitHub/Brief12/MovieWise_Recommender_System/your_mlflow_uri/0
creation_time: 1707839589792
experiment_id: '0'
last_update_time: 1707839589792
lifecycle_stage: active
name: Default
