artifact_uri: file:///c:/Users/Utilisateur/Documents/GitHub/Brief12/MovieWise_Recommender_System/your_mlflow_uri/342564443274030358/698cc0e774cd4f78b3d6fc6f9dff63bd/artifacts
end_time: 1707840063653
entry_point_name: ''
experiment_id: '342564443274030358'
lifecycle_stage: active
run_id: 698cc0e774cd4f78b3d6fc6f9dff63bd
run_name: victorious-hare-663
run_uuid: 698cc0e774cd4f78b3d6fc6f9dff63bd
source_name: ''
source_type: 4
source_version: ''
start_time: 1707840063211
status: 3
tags: []
user_id: Utilisateur
