artifact_uri: file:///c:/Users/Utilisateur/Documents/GitHub/Brief12/MovieWise_Recommender_System/your_mlflow_uri/342564443274030358/5f1cf30aaa304db69149f98f782ce6bb/artifacts
end_time: 1707840061453
entry_point_name: ''
experiment_id: '342564443274030358'
lifecycle_stage: active
run_id: 5f1cf30aaa304db69149f98f782ce6bb
run_name: trusting-smelt-103
run_uuid: 5f1cf30aaa304db69149f98f782ce6bb
source_name: ''
source_type: 4
source_version: ''
start_time: 1707840060793
status: 3
tags: []
user_id: Utilisateur
