artifact_uri: file:///c:/Users/Utilisateur/Documents/GitHub/Brief12/MovieWise_Recommender_System/your_mlflow_uri/342564443274030358/cc1ab3a2387744a7aa9bc701cf837c44/artifacts
end_time: 1707839648128
entry_point_name: ''
experiment_id: '342564443274030358'
lifecycle_stage: active
run_id: cc1ab3a2387744a7aa9bc701cf837c44
run_name: sincere-hawk-494
run_uuid: cc1ab3a2387744a7aa9bc701cf837c44
source_name: ''
source_type: 4
source_version: ''
start_time: 1707839646725
status: 3
tags: []
user_id: Utilisateur
