artifact_uri: file:///c:/Users/Utilisateur/Documents/GitHub/Brief12/MovieWise_Recommender_System/your_mlflow_uri/342564443274030358/1f3118eb51b74ab1a0f6fcf0dba22d1d/artifacts
end_time: 1707839700735
entry_point_name: ''
experiment_id: '342564443274030358'
lifecycle_stage: active
run_id: 1f3118eb51b74ab1a0f6fcf0dba22d1d
run_name: treasured-jay-460
run_uuid: 1f3118eb51b74ab1a0f6fcf0dba22d1d
source_name: ''
source_type: 4
source_version: ''
start_time: 1707839699487
status: 3
tags: []
user_id: Utilisateur
