artifact_uri: file:///c:/Users/Utilisateur/Documents/GitHub/Brief12/MovieWise_Recommender_System/your_mlflow_uri/342564443274030358/bfbd0e4ff8d942c7a3521f1190f0cea9/artifacts
end_time: 1707839876195
entry_point_name: ''
experiment_id: '342564443274030358'
lifecycle_stage: active
run_id: bfbd0e4ff8d942c7a3521f1190f0cea9
run_name: delightful-crow-47
run_uuid: bfbd0e4ff8d942c7a3521f1190f0cea9
source_name: ''
source_type: 4
source_version: ''
start_time: 1707839873403
status: 3
tags: []
user_id: Utilisateur
