artifact_uri: file:///c:/Users/Utilisateur/Documents/GitHub/Brief12/MovieWise_Recommender_System/your_mlflow_uri/342564443274030358/67a7b27d58fa4e3c9d9c3d277fa68b74/artifacts
end_time: 1707840048600
entry_point_name: ''
experiment_id: '342564443274030358'
lifecycle_stage: active
run_id: 67a7b27d58fa4e3c9d9c3d277fa68b74
run_name: unruly-goat-449
run_uuid: 67a7b27d58fa4e3c9d9c3d277fa68b74
source_name: ''
source_type: 4
source_version: ''
start_time: 1707840045651
status: 3
tags: []
user_id: Utilisateur
