artifact_uri: file:///c:/Users/Utilisateur/Documents/GitHub/Brief12/MovieWise_Recommender_System/your_mlflow_uri/342564443274030358/70678c93cd924460b44cd95a3dedae1a/artifacts
end_time: 1707839644561
entry_point_name: ''
experiment_id: '342564443274030358'
lifecycle_stage: active
run_id: 70678c93cd924460b44cd95a3dedae1a
run_name: bright-panda-633
run_uuid: 70678c93cd924460b44cd95a3dedae1a
source_name: ''
source_type: 4
source_version: ''
start_time: 1707839644066
status: 3
tags: []
user_id: Utilisateur
