artifact_uri: file:///c:/Users/Utilisateur/Documents/GitHub/Brief12/MovieWise_Recommender_System/your_mlflow_uri/342564443274030358/b55db94ffa7f4cfca34d60018374edb0/artifacts
end_time: 1707839885790
entry_point_name: ''
experiment_id: '342564443274030358'
lifecycle_stage: active
run_id: b55db94ffa7f4cfca34d60018374edb0
run_name: persistent-mole-105
run_uuid: b55db94ffa7f4cfca34d60018374edb0
source_name: ''
source_type: 4
source_version: ''
start_time: 1707839884487
status: 3
tags: []
user_id: Utilisateur
