artifact_uri: file:///c:/Users/Utilisateur/Documents/GitHub/Brief12/MovieWise_Recommender_System/your_mlflow_uri/342564443274030358/30300bec3fb143caa88a78da0f3db514/artifacts
end_time: 1707839847912
entry_point_name: ''
experiment_id: '342564443274030358'
lifecycle_stage: active
run_id: 30300bec3fb143caa88a78da0f3db514
run_name: suave-shoat-461
run_uuid: 30300bec3fb143caa88a78da0f3db514
source_name: ''
source_type: 4
source_version: ''
start_time: 1707839845102
status: 3
tags: []
user_id: Utilisateur
