artifact_uri: file:///c:/Users/Utilisateur/Documents/GitHub/Brief12/MovieWise_Recommender_System/your_mlflow_uri/342564443274030358/5fb6f4ec33884829a42a0c7e3bcd6c47/artifacts
end_time: 1707839711312
entry_point_name: ''
experiment_id: '342564443274030358'
lifecycle_stage: active
run_id: 5fb6f4ec33884829a42a0c7e3bcd6c47
run_name: nosy-trout-559
run_uuid: 5fb6f4ec33884829a42a0c7e3bcd6c47
source_name: ''
source_type: 4
source_version: ''
start_time: 1707839710461
status: 3
tags: []
user_id: Utilisateur
