artifact_location: file:///c:/Users/Utilisateur/Documents/GitHub/Brief12/MovieWise_Recommender_System/your_mlflow_uri/342564443274030358
creation_time: 1707839589818
experiment_id: '342564443274030358'
last_update_time: 1707839589818
lifecycle_stage: active
name: your_experiment_name
