artifact_uri: file:///c:/Users/Utilisateur/Documents/GitHub/Brief12/MovieWise_Recommender_System/your_mlflow_uri/342564443274030358/95859e485add47afae1faa9a00c81b79/artifacts
end_time: 1707839914646
entry_point_name: ''
experiment_id: '342564443274030358'
lifecycle_stage: active
run_id: 95859e485add47afae1faa9a00c81b79
run_name: fortunate-lamb-70
run_uuid: 95859e485add47afae1faa9a00c81b79
source_name: ''
source_type: 4
source_version: ''
start_time: 1707839913832
status: 3
tags: []
user_id: Utilisateur
