artifact_uri: file:///c:/Users/Utilisateur/Documents/GitHub/Brief12/MovieWise_Recommender_System/your_mlflow_uri/342564443274030358/8f11136ffaa243b19f08fc34dd63bc4c/artifacts
end_time: 1707839716892
entry_point_name: ''
experiment_id: '342564443274030358'
lifecycle_stage: active
run_id: 8f11136ffaa243b19f08fc34dd63bc4c
run_name: upbeat-crow-153
run_uuid: 8f11136ffaa243b19f08fc34dd63bc4c
source_name: ''
source_type: 4
source_version: ''
start_time: 1707839716017
status: 3
tags: []
user_id: Utilisateur
