artifact_uri: file:///c:/Users/Utilisateur/Documents/GitHub/Brief12/MovieWise_Recommender_System/your_mlflow_uri/342564443274030358/99e88c0bdcf747cab0777ada5b46ee5c/artifacts
end_time: 1707839838546
entry_point_name: ''
experiment_id: '342564443274030358'
lifecycle_stage: active
run_id: 99e88c0bdcf747cab0777ada5b46ee5c
run_name: sedate-asp-730
run_uuid: 99e88c0bdcf747cab0777ada5b46ee5c
source_name: ''
source_type: 4
source_version: ''
start_time: 1707839837917
status: 3
tags: []
user_id: Utilisateur
