artifact_uri: file:///c:/Users/Utilisateur/Documents/GitHub/Brief12/MovieWise_Recommender_System/your_mlflow_uri/342564443274030358/ed88acee3beb471dbbe30ff88bd01d41/artifacts
end_time: 1707840026933
entry_point_name: ''
experiment_id: '342564443274030358'
lifecycle_stage: active
run_id: ed88acee3beb471dbbe30ff88bd01d41
run_name: magnificent-seal-773
run_uuid: ed88acee3beb471dbbe30ff88bd01d41
source_name: ''
source_type: 4
source_version: ''
start_time: 1707840026305
status: 3
tags: []
user_id: Utilisateur
