artifact_uri: file:///c:/Users/Utilisateur/Documents/GitHub/Brief12/MovieWise_Recommender_System/your_mlflow_uri/342564443274030358/da9b6e5fa75147e0a71f89411a1bd3e5/artifacts
end_time: 1707839830131
entry_point_name: ''
experiment_id: '342564443274030358'
lifecycle_stage: active
run_id: da9b6e5fa75147e0a71f89411a1bd3e5
run_name: skillful-doe-62
run_uuid: da9b6e5fa75147e0a71f89411a1bd3e5
source_name: ''
source_type: 4
source_version: ''
start_time: 1707839829214
status: 3
tags: []
user_id: Utilisateur
