artifact_uri: file:///c:/Users/Utilisateur/Documents/GitHub/Brief12/MovieWise_Recommender_System/your_mlflow_uri/342564443274030358/68d64e6425ef4e66bb5fadb425bf2a05/artifacts
end_time: 1707839655675
entry_point_name: ''
experiment_id: '342564443274030358'
lifecycle_stage: active
run_id: 68d64e6425ef4e66bb5fadb425bf2a05
run_name: bouncy-toad-325
run_uuid: 68d64e6425ef4e66bb5fadb425bf2a05
source_name: ''
source_type: 4
source_version: ''
start_time: 1707839655253
status: 3
tags: []
user_id: Utilisateur
