artifact_uri: file:///c:/Users/Utilisateur/Documents/GitHub/Brief12/MovieWise_Recommender_System/your_mlflow_uri/342564443274030358/4703f4625d5b4d3cac2926deaa90e2cb/artifacts
end_time: 1707839918893
entry_point_name: ''
experiment_id: '342564443274030358'
lifecycle_stage: active
run_id: 4703f4625d5b4d3cac2926deaa90e2cb
run_name: rebellious-elk-164
run_uuid: 4703f4625d5b4d3cac2926deaa90e2cb
source_name: ''
source_type: 4
source_version: ''
start_time: 1707839918056
status: 3
tags: []
user_id: Utilisateur
