artifact_uri: file:///c:/Users/Utilisateur/Documents/GitHub/Brief12/MovieWise_Recommender_System/your_mlflow_uri/342564443274030358/ac0fea6c2fdf4d518a78c7daba42c220/artifacts
end_time: 1707839819044
entry_point_name: ''
experiment_id: '342564443274030358'
lifecycle_stage: active
run_id: ac0fea6c2fdf4d518a78c7daba42c220
run_name: treasured-whale-911
run_uuid: ac0fea6c2fdf4d518a78c7daba42c220
source_name: ''
source_type: 4
source_version: ''
start_time: 1707839818210
status: 3
tags: []
user_id: Utilisateur
