artifact_uri: file:///c:/Users/Utilisateur/Documents/GitHub/Brief12/MovieWise_Recommender_System/your_mlflow_uri/342564443274030358/cf8414fa2f484f2eb57f49af377f43f9/artifacts
end_time: 1707839901661
entry_point_name: ''
experiment_id: '342564443274030358'
lifecycle_stage: active
run_id: cf8414fa2f484f2eb57f49af377f43f9
run_name: placid-shrimp-594
run_uuid: cf8414fa2f484f2eb57f49af377f43f9
source_name: ''
source_type: 4
source_version: ''
start_time: 1707839899683
status: 3
tags: []
user_id: Utilisateur
