artifact_uri: file:///c:/Users/Utilisateur/Documents/GitHub/Brief12/MovieWise_Recommender_System/your_mlflow_uri/342564443274030358/5da4ad7c026e4d259ef38bede44f5d74/artifacts
end_time: 1707839912184
entry_point_name: ''
experiment_id: '342564443274030358'
lifecycle_stage: active
run_id: 5da4ad7c026e4d259ef38bede44f5d74
run_name: clumsy-bird-180
run_uuid: 5da4ad7c026e4d259ef38bede44f5d74
source_name: ''
source_type: 4
source_version: ''
start_time: 1707839911386
status: 3
tags: []
user_id: Utilisateur
