artifact_uri: file:///c:/Users/Utilisateur/Documents/GitHub/Brief12/MovieWise_Recommender_System/your_mlflow_uri/342564443274030358/4db301058b3d48a1a766b46cabd2ced4/artifacts
end_time: 1707839677141
entry_point_name: ''
experiment_id: '342564443274030358'
lifecycle_stage: active
run_id: 4db301058b3d48a1a766b46cabd2ced4
run_name: enchanting-stork-338
run_uuid: 4db301058b3d48a1a766b46cabd2ced4
source_name: ''
source_type: 4
source_version: ''
start_time: 1707839675413
status: 3
tags: []
user_id: Utilisateur
