artifact_uri: file:///c:/Users/Utilisateur/Documents/GitHub/Brief12/MovieWise_Recommender_System/your_mlflow_uri/342564443274030358/b2b05e3501ed440fa8d90ba7091be95c/artifacts
end_time: 1707840043780
entry_point_name: ''
experiment_id: '342564443274030358'
lifecycle_stage: active
run_id: b2b05e3501ed440fa8d90ba7091be95c
run_name: agreeable-hawk-400
run_uuid: b2b05e3501ed440fa8d90ba7091be95c
source_name: ''
source_type: 4
source_version: ''
start_time: 1707840042621
status: 3
tags: []
user_id: Utilisateur
