artifact_uri: file:///c:/Users/Utilisateur/Documents/GitHub/Brief12/MovieWise_Recommender_System/your_mlflow_uri/342564443274030358/ffdda12d387647fdb5c0413cb8f6e10d/artifacts
end_time: 1707840008152
entry_point_name: ''
experiment_id: '342564443274030358'
lifecycle_stage: active
run_id: ffdda12d387647fdb5c0413cb8f6e10d
run_name: dapper-sponge-771
run_uuid: ffdda12d387647fdb5c0413cb8f6e10d
source_name: ''
source_type: 4
source_version: ''
start_time: 1707840007468
status: 3
tags: []
user_id: Utilisateur
