artifact_uri: file:///c:/Users/Utilisateur/Documents/GitHub/Brief12/MovieWise_Recommender_System/your_mlflow_uri/342564443274030358/628fdcee960b4de3a614911ab6c963c3/artifacts
end_time: 1707839817254
entry_point_name: ''
experiment_id: '342564443274030358'
lifecycle_stage: active
run_id: 628fdcee960b4de3a614911ab6c963c3
run_name: silent-goose-905
run_uuid: 628fdcee960b4de3a614911ab6c963c3
source_name: ''
source_type: 4
source_version: ''
start_time: 1707839816772
status: 3
tags: []
user_id: Utilisateur
