artifact_uri: file:///c:/Users/Utilisateur/Documents/GitHub/Brief12/MovieWise_Recommender_System/your_mlflow_uri/342564443274030358/253ee808149149afaaaec0061110fdae/artifacts
end_time: 1707840013981
entry_point_name: ''
experiment_id: '342564443274030358'
lifecycle_stage: active
run_id: 253ee808149149afaaaec0061110fdae
run_name: luxuriant-robin-484
run_uuid: 253ee808149149afaaaec0061110fdae
source_name: ''
source_type: 4
source_version: ''
start_time: 1707840013524
status: 3
tags: []
user_id: Utilisateur
