artifact_uri: file:///c:/Users/Utilisateur/Documents/GitHub/Brief12/MovieWise_Recommender_System/your_mlflow_uri/342564443274030358/3c4fc58a4c1f472e85ede62281c6d49c/artifacts
end_time: 1707839821788
entry_point_name: ''
experiment_id: '342564443274030358'
lifecycle_stage: active
run_id: 3c4fc58a4c1f472e85ede62281c6d49c
run_name: nervous-ape-244
run_uuid: 3c4fc58a4c1f472e85ede62281c6d49c
source_name: ''
source_type: 4
source_version: ''
start_time: 1707839820687
status: 3
tags: []
user_id: Utilisateur
