artifact_uri: file:///c:/Users/Utilisateur/Documents/GitHub/Brief12/MovieWise_Recommender_System/your_mlflow_uri/342564443274030358/e5b068be81714d68986a5a0de7cd61af/artifacts
end_time: 1707839594023
entry_point_name: ''
experiment_id: '342564443274030358'
lifecycle_stage: active
run_id: e5b068be81714d68986a5a0de7cd61af
run_name: ambitious-flea-616
run_uuid: e5b068be81714d68986a5a0de7cd61af
source_name: ''
source_type: 4
source_version: ''
start_time: 1707839592464
status: 3
tags: []
user_id: Utilisateur
