artifact_uri: file:///c:/Users/Utilisateur/Documents/GitHub/Brief12/MovieWise_Recommender_System/your_mlflow_uri/342564443274030358/0abf6de2a02245c5bac339f1db0f20bc/artifacts
end_time: 1707839916803
entry_point_name: ''
experiment_id: '342564443274030358'
lifecycle_stage: active
run_id: 0abf6de2a02245c5bac339f1db0f20bc
run_name: charming-stoat-562
run_uuid: 0abf6de2a02245c5bac339f1db0f20bc
source_name: ''
source_type: 4
source_version: ''
start_time: 1707839916036
status: 3
tags: []
user_id: Utilisateur
