artifact_uri: file:///c:/Users/Utilisateur/Documents/GitHub/Brief12/MovieWise_Recommender_System/your_mlflow_uri/342564443274030358/b7df2de6bed94a71ad40334b505dfbad/artifacts
end_time: 1707839650988
entry_point_name: ''
experiment_id: '342564443274030358'
lifecycle_stage: active
run_id: b7df2de6bed94a71ad40334b505dfbad
run_name: casual-dove-810
run_uuid: b7df2de6bed94a71ad40334b505dfbad
source_name: ''
source_type: 4
source_version: ''
start_time: 1707839650035
status: 3
tags: []
user_id: Utilisateur
