artifact_uri: file:///c:/Users/Utilisateur/Documents/GitHub/Brief12/MovieWise_Recommender_System/your_mlflow_uri/342564443274030358/9d3bdaec1a814491b3eaf4f72086a60b/artifacts
end_time: 1707840016540
entry_point_name: ''
experiment_id: '342564443274030358'
lifecycle_stage: active
run_id: 9d3bdaec1a814491b3eaf4f72086a60b
run_name: nebulous-shrike-352
run_uuid: 9d3bdaec1a814491b3eaf4f72086a60b
source_name: ''
source_type: 4
source_version: ''
start_time: 1707840015712
status: 3
tags: []
user_id: Utilisateur
