artifact_uri: file:///c:/Users/Utilisateur/Documents/GitHub/Brief12/MovieWise_Recommender_System/your_mlflow_uri/342564443274030358/e8fcca1f304f41d89a3803efaa094166/artifacts
end_time: 1707839595911
entry_point_name: ''
experiment_id: '342564443274030358'
lifecycle_stage: active
run_id: e8fcca1f304f41d89a3803efaa094166
run_name: smiling-rat-27
run_uuid: e8fcca1f304f41d89a3803efaa094166
source_name: ''
source_type: 4
source_version: ''
start_time: 1707839595396
status: 3
tags: []
user_id: Utilisateur
