artifact_uri: file:///c:/Users/Utilisateur/Documents/GitHub/Brief12/MovieWise_Recommender_System/your_mlflow_uri/342564443274030358/dfcc373bd2c841f3af997b7c63cafcbc/artifacts
end_time: 1707839898398
entry_point_name: ''
experiment_id: '342564443274030358'
lifecycle_stage: active
run_id: dfcc373bd2c841f3af997b7c63cafcbc
run_name: gaudy-stoat-545
run_uuid: dfcc373bd2c841f3af997b7c63cafcbc
source_name: ''
source_type: 4
source_version: ''
start_time: 1707839896723
status: 3
tags: []
user_id: Utilisateur
