artifact_uri: file:///c:/Users/Utilisateur/Documents/GitHub/Brief12/MovieWise_Recommender_System/your_mlflow_uri/342564443274030358/ac2ca18a40f24eca89bd653ef3ed2e9d/artifacts
end_time: 1707839806186
entry_point_name: ''
experiment_id: '342564443274030358'
lifecycle_stage: active
run_id: ac2ca18a40f24eca89bd653ef3ed2e9d
run_name: chill-fly-578
run_uuid: ac2ca18a40f24eca89bd653ef3ed2e9d
source_name: ''
source_type: 4
source_version: ''
start_time: 1707839804740
status: 3
tags: []
user_id: Utilisateur
