artifact_uri: file:///c:/Users/Utilisateur/Documents/GitHub/Brief12/MovieWise_Recommender_System/your_mlflow_uri/342564443274030358/e71effd3ec774ff1aa448126288f7b4a/artifacts
end_time: 1707839841802
entry_point_name: ''
experiment_id: '342564443274030358'
lifecycle_stage: active
run_id: e71effd3ec774ff1aa448126288f7b4a
run_name: defiant-bear-124
run_uuid: e71effd3ec774ff1aa448126288f7b4a
source_name: ''
source_type: 4
source_version: ''
start_time: 1707839840434
status: 3
tags: []
user_id: Utilisateur
