artifact_uri: file:///c:/Users/Utilisateur/Documents/GitHub/Brief12/MovieWise_Recommender_System/your_mlflow_uri/342564443274030358/6a7b962c234d4aefa03bc1429bfbcbf1/artifacts
end_time: 1707839849162
entry_point_name: ''
experiment_id: '342564443274030358'
lifecycle_stage: active
run_id: 6a7b962c234d4aefa03bc1429bfbcbf1
run_name: defiant-fawn-907
run_uuid: 6a7b962c234d4aefa03bc1429bfbcbf1
source_name: ''
source_type: 4
source_version: ''
start_time: 1707839847940
status: 3
tags: []
user_id: Utilisateur
